#!/bin/bash

GXX=/usr/local/cs/bin/g++
[ -x $GXX ] || GXX=/usr/bin/g++

RPATH='-Wl,-rpath=/usr/local/cs/lib64'
WARNINGS='-Wall -Wextra -Wno-sign-compare -Werror=return-type -Wno-unknown-pragmas -Werror=vla'

STD='-std=c++17'
SAN='-fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer'
SAN2='-fsanitize=bounds'
OPT=

case $($GXX --version | head -1) in
 *\ 4.9*)               SAN2= ; STD='-std=c++14' ;;
 *\ 4.8*)               SAN2= ; SAN= ; STD='-std=c++11' ;;
 *\ 4.[3-7]*)   SAN2= ; SAN= ; STD='-std=c++0x' ;;
esac

case $0 in
 *fast) SAN2= ; SAN= ; OPT='-O2' ;;
esac

$GXX $STD $SAN $SAN2 $OPT $WARNINGS $RPATH "$@" -lpthread
